name: Go Code Quality and Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Check Go Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Run gofumpt
        run: |
          gofumpt -l -w .
          git diff --exit-code

      - name: Prompt for fixes and halt workflow on formatting issues
        if: ${{ failure() }}
        run: |
          echo "Code formatting issues found. Please run 'gofumpt -l -w .' locally to fix formatting."
          exit 1

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Install dependencies
        run: go mod download

      - name: Run tests with makefile
        run: make test
