name: Tests

on:
  workflow_run:
    workflows: ["Go Formatting"]
    types:
      - completed

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1

      - name: Install dependencies
        run: go mod download

      - name: Run tests with makefile
        run: make test
